### ISSUE TITLE
Building Issue

### ISSUE THREAD

**Issue by alteirac** [axkibe/lsyncd#544]
Hello
I have some issues when i try to build lsyncd :
cmake .
-- The C compiler identification is GNU 8.2.1
-- The CXX compiler identification is GNU 8.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Lua: /usr/lib/liblua.so;/usr/lib/libm.so (found version "") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/thierry/Données/Installation/lsyncd-release-2.1.6

make
[ 10%] Generating defaults.out
Compiling built-in default configs
[ 20%] Generating runner.out
Compiling built-in runner
[ 30%] Generating runner.c
Generating built-in runner linkable
[ 40%] Generating defaults.c
Generating built-in default configs
Scanning dependencies of target lsyncd
[ 50%] Building C object CMakeFiles/lsyncd.dir/lsyncd.c.o
In file included from /usr/include/signal.h:25,
                 from /home/thierry/Données/Installation/lsyncd-release-2.1.6/lsyncd.h:24,
                 from /home/thierry/Données/Installation/lsyncd-release-2.1.6/lsyncd.c:18:
/usr/include/features.h:184:3: warning: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Wcpp]
 # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
   ^~~~~~~
/home/thierry/Données/Installation/lsyncd-release-2.1.6/lsyncd.c: Dans la fonction « l_exec »:
/home/thierry/Données/Installation/lsyncd-release-2.1.6/lsyncd.c:1118:41: warning: déclaration implicite de la fonction « lua_objlen »; vouliez-vous utiliser « lua_len » ? [-Wimplicit-function-declaration]
    lua_checkstack( L, lua_gettop( L ) + lua_objlen( L, i ) + 1 );
                                         ^~~~~~~~~~
                                         lua_len
/home/thierry/Données/Installation/lsyncd-release-2.1.6/lsyncd.c: Dans la fonction « register_lsyncd »:
/home/thierry/Données/Installation/lsyncd-release-2.1.6/lsyncd.c:1900:2: warning: déclaration implicite de la fonction « luaL_register »; vouliez-vous utiliser « lua_register » ? [-Wimplicit-function-declaration]
  luaL_register( L, LSYNCD_LIBNAME, lsyncdlib );
  ^~~~~~~~~~~~~
  lua_register
[ 60%] Building C object CMakeFiles/lsyncd.dir/runner.c.o
[ 70%] Building C object CMakeFiles/lsyncd.dir/defaults.c.o
[ 80%] Building C object CMakeFiles/lsyncd.dir/inotify.c.o
In file included from /usr/include/signal.h:25,
                 from /home/thierry/Données/Installation/lsyncd-release-2.1.6/lsyncd.h:24,
                 from /home/thierry/Données/Installation/lsyncd-release-2.1.6/inotify.c:13:
/usr/include/features.h:184:3: warning: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Wcpp]
 # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
   ^~~~~~~
/home/thierry/Données/Installation/lsyncd-release-2.1.6/inotify.c: Dans la fonction « register_inotify »:
/home/thierry/Données/Installation/lsyncd-release-2.1.6/inotify.c:498:2: warning: déclaration implicite de la fonction « luaL_register »; vouliez-vous utiliser « lua_register » ? [-Wimplicit-function-declaration]
  luaL_register( L, LSYNCD_INOTIFYLIBNAME, linotfylib );
  ^~~~~~~~~~~~~
  lua_register
[ 90%] Linking C executable lsyncd
/usr/bin/ld: CMakeFiles/lsyncd.dir/lsyncd.c.o: in function `l_exec':
lsyncd.c:(.text+0x17d8): undefined reference to `lua_objlen'
/usr/bin/ld: lsyncd.c:(.text+0x1855): undefined reference to `lua_objlen'
/usr/bin/ld: CMakeFiles/lsyncd.dir/lsyncd.c.o: in function `register_lsyncd':
lsyncd.c:(.text+0x3448): undefined reference to `luaL_register'
/usr/bin/ld: CMakeFiles/lsyncd.dir/inotify.c.o: in function `register_inotify':
inotify.c:(.text+0xa6b): undefined reference to `luaL_register'
collect2: error: ld a retourné le statut de sortie 1
make[2]: *** [CMakeFiles/lsyncd.dir/build.make:154: lsyncd] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/lsyncd.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

Some body can help ? 

pacman -Qs cmake : local/cmake 3.13.1-1
pacman -Qs lua : 
              local/lua 5.3.5-1
              local/lua52 5.2.4-3
              local/lua52-bitop 1.0.2-8
              local/lua52-expat 1.3.0-4
              local/lua52-lpeg 1.0.1-2
              local/lua52-luajson 1.3.4-1
              local/lua52-socket 20160311-2

**Comment by axkibe** [comment]
I believe you are trying to build against Lua 5.3

Lsyncd 2.2 works with Lua 5.1 and 5.2
5.3 (in devel tree) will work with 5.2 and 5.3

I find it hard to support more than two Lua versions at a time...

**Comment by isarandi** [comment]
> I believe you are trying to build against Lua 5.3
> 
> Lsyncd 2.2 works with Lua 5.1 and 5.2

It would be nice to change the ChangeLog to reflect this. Currently it explicitly says Lua 5.3 is supported.
