### ISSUE TITLE
doesn't compile on CentOS 7.4.1708

### ISSUE THREAD

**Issue by NikitaVoitov** [axkibe/lsyncd#498]
root@c7-la ~# cd lsyncd-master/
root@c7-la ~/lsyncd-master# cmake .
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Lua: /usr/lib64/liblua-5.3.so;/usr/lib64/libm.so
-- Configuring done
-- Generating done
-- Build files have been written to: /root/lsyncd-master
root@c7-la ~/lsyncd-master# make
[ 12%] Generating defaults.out
Compiling built-in default configs
[ 25%] Generating runner.out
Compiling built-in runner
[ 37%] Generating runner.c
Generating built-in runner linkable
[ 50%] Generating defaults.c
Generating built-in default configs
Scanning dependencies of target lsyncd
[ 62%] Building C object CMakeFiles/lsyncd.dir/lsyncd.c.o
/root/lsyncd-master/lsyncd.c: In function ‘l_readdir’:
/root/lsyncd-master/lsyncd.c:1527:21: error: ‘DT_UNKNOWN’ undeclared (first use in this function)
   if( de->d_type == DT_UNKNOWN )
                     ^
/root/lsyncd-master/lsyncd.c:1527:21: note: each undeclared identifier is reported only once for each function it appears in
/root/lsyncd-master/lsyncd.c:1552:26: error: ‘DT_DIR’ undeclared (first use in this function)
    isdir = de->d_type == DT_DIR;
                          ^
make[2]: *** [CMakeFiles/lsyncd.dir/lsyncd.c.o] Error 1
make[1]: *** [CMakeFiles/lsyncd.dir/all] Error 2
make: *** [all] Error 2

root@c7-la ~/lsyncd-master# cmake --version
cmake version 2.8.12.2
root@c7-la ~/lsyncd-master# sysctl fs.inotify
fs.inotify.max_queued_events = 16384
fs.inotify.max_user_instances = 128
fs.inotify.max_user_watches = 8192
root@c7-la ~/lsyncd-master# uname -a
Linux c7-la.local.lab 3.10.0-693.17.1.el7.x86_64 #1 SMP Thu Jan 25 20:13:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
root@c7-la ~/lsyncd-master# cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)

Any thoughts why?

**Comment by svenha** [comment]
Is your compter missing the file /usr/include/dirent.h ?

**Comment by axkibe** [comment]
That would have given a different error, I don't know why dirent.h doesn't define these values for use.

Prolly some feature Macro missing?

**Comment by NikitaVoitov** [comment]
root@c7-la ~# file /usr/include/dirent.h
/usr/include/dirent.h: C source, ASCII text
root@c7-la ~# less /usr/include/dirent.h
root@c7-la ~# grep 'DT_UNKNOWN' /usr/include/dirent.h
    DT_UNKNOWN = 0,
# define DT_UNKNOWN     DT_UNKNOWN
root@c7-la ~# grep 'DT_DIR' /usr/include/dirent.h
    DT_DIR = 4,
# define DT_DIR         DT_DIR

**Comment by axkibe** [comment]
And if you make a safety copy of the file and add a
#error
in exactly that line you will likely see it is #ifdef'ed out, out of some reason.

**Comment by NikitaVoitov** [comment]
okay, it there a workaround or how can I fix it?

**Comment by axkibe** [comment]
Figure out why it's not defined in header on your system. Some #if or #ifdef must exclude it. It may a be a bit of digging required going through the header hiearchy.

**Comment by NikitaVoitov** [comment]
ok, thanks, I will follow your suggestions

**Comment by mdciotti** [comment]
I solved this problem on CentOS 7 after some digging. I simply removed the condition and `else` block from the `if` statement at [line 1527 of `lsyncd.c`](https://github.com/axkibe/lsyncd/blob/master/lsyncd.c#L1527), keeping only the first block.

I then added a `-ldl` flag to the linker. I wasn't sure how to update this within CMake but I verified it works by manually modifying `CMakeFiles/lsyncd.dir/link.txt`.

Maybe this isn't a good universal solution, but if you want I can make a pull request so you can at least see the changes I made. For whatever reason, my system has `/usr/include/dirent.h` but won't set the enum variables `DT_UNKNOWN` and `DT_DIR`, even when manually toggling `__USE_BSD` and ensuring the header is included.

**Comment by axkibe** [comment]
As this issue is solved for you, albeit we didn't find the real reason the specific feature set is not unlocked in your header file configuration, I'll close this issue.

**Comment by clonemeagain** [comment]
Just to chime in, this is also the case with latest releast on my Debian 7 box.
Latest master built fine (I think fixed in https://github.com/axkibe/lsyncd/commit/42413cabbedca429d55a5378f6e830f191f3cc86)
