### ISSUE TITLE
Lua 5.2 support

### ISSUE THREAD

**Issue by devurandom** [axkibe/lsyncd#146]
lsyncd-2.0.7 fails to compile with Lua 5.2, see for example the Gentoo bug on the matter [1].

The error is:
x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I.     -pipe -O2 -march=athlon64-sse3 -Wall  -c inotify.c
inotify.c:132:1: error: unknown type name ‘luaL_reg’
[…]

A complete build.log is available at abovementioned report.

[1] https://bugs.gentoo.org/show_bug.cgi?id=434238
